baseURL = 'https://scp096.github.io/'
languageCode = "zh-CN"
languageName = "简体中文"
title = 'scp的扯淡时间'
theme = 'LoveIt'

[author]
  name = "scp096"
  email = "crazyinchina@outlook.com"
  link = "scp096.github.io"

[params]
  description = "随便谈谈"
  [params.header]
    [params.header.title]
      name = "scp的扯淡时间"
    [params.home.profile]
      typeit = false
      subtitle = "随便谈谈"